[platformio]
default_envs = bratan

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:bratan]
build_flags =
    ${env.build_flags}
    -DNODE_BRATAN=1

[env:chuvak]
build_flags =
    ${env.build_flags}
    -DNODE_CHUVAK=1
